"""Stable codes for package / vendor / compose failures."""

from __future__ import annotations


class PackageError(ValueError):
    def __init__(self, code: str, message: str) -> None:
        self.code = code
        super().__init__(message)


PX_PKG_MANIFEST_INVALID = "PX_PKG_MANIFEST_INVALID"
PX_PKG_LOCK_INVALID = "PX_PKG_LOCK_INVALID"
PX_PKG_NOT_FOUND = "PX_PKG_NOT_FOUND"
PX_PKG_FINGERPRINT_MISMATCH = "PX_PKG_FINGERPRINT_MISMATCH"
PX_PKG_SOURCE_UNSUPPORTED = "PX_PKG_SOURCE_UNSUPPORTED"
PX_PKG_MERGE_FORBIDDEN_KEY = "PX_PKG_MERGE_FORBIDDEN_KEY"
PX_PKG_MERGE_CONDITION_ID_COLLISION = "PX_PKG_MERGE_CONDITION_ID_COLLISION"
PX_PKG_MERGE_INPUT_CONFLICT = "PX_PKG_MERGE_INPUT_CONFLICT"
PX_PKG_COMPOSE_SPEC = "PX_PKG_COMPOSE_SPEC"
PX_PKG_REF_INVALID = "PX_PKG_REF_INVALID"
PX_PKG_REGISTRY_INVALID = "PX_PKG_REGISTRY_INVALID"
PX_PKG_FETCH_FAILED = "PX_PKG_FETCH_FAILED"
PX_PKG_ARTIFACT_FAILED = "PX_PKG_ARTIFACT_FAILED"
